# Generated by Django 5.2 on 2025-04-25 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=256)),
                ('img', models.CharField(max_length=256)),
                ('surface', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Appareil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=256)),
                ('img', models.CharField(max_length=256)),
                ('actif', models.BooleanField()),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appareil.piece')),
            ],
        ),
    ]
