# Generated by Django 5.1.7 on 2025-04-15 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='appareil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=256)),
                ('piece', models.CharField(max_length=256)),
                ('img', models.CharField(max_length=256)),
                ('actif', models.BooleanField()),
            ],
        ),
    ]
