# Generated by Django 5.2 on 2025-04-25 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appareil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appareil',
            name='img',
            field=models.ImageField(upload_to='appareils/'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='img',
            field=models.ImageField(upload_to='pieces/'),
        ),
    ]
